name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: Build SDist
       run: pipx run build --sdist

     - name: Check metadata
       run: pipx run twine check dist/*

     - uses: actions/upload-artifact@v3
       with:
         path: dist/*.tar.gz

  pip_install:
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest, macos-latest, ubuntu-latest ]
        python-version: [ "3.8" ]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add requirements
        run: python -m pip install --upgrade -r requirements.txt

      - name: Add test and format requirements
        run: python -m pip install --upgrade pytest flake8

      - name: Build and install
        run: pip install --verbose -e .

      - name: flake8
        run: flake8 ./src ./tests

  upload_pypi:
    name: Upload to pypi
    needs: [build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
     - uses: actions/setup-python@v4
       with:
         python-version: "3.8"

     - uses: actions/download-artifact@v3
       with:
         name: artifact
         path: dist

     - uses: pypa/gh-action-pypi-publish@release/v1
       with:
         password: ${{ secrets.PYPI_API_TOKEN }}


