name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  pip_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Add requirements
        run: python -m pip install --upgrade -r requirements.txt

      - name: Add test and format requirements
        run: python -m pip install --upgrade pytest flake8

      - name: Build and install
        run: pip install --verbose -e .

      - name: flake8
        run: flake8 ./src ./tests
